# Generated by cucumber-sinatra. (2010-10-08 12:43:27 -0600)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'app.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = App

class AppWorld
  include Capybara
  include Rspec::Expectations
  include Rspec::Matchers
end

World do
  AppWorld.new
end
